ci: elaborate on testing strategy

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -48,10 +48,12 @@ jobs:
     - name: Test with pytest
       env:
         DCOR_API_KEY: ${{ secrets.DCOR_API_KEY }}
+      # Tests always pass but pytest sometimes fails with 138 or 139 due
+      # to threading issues. We always exit 0 here and check in the next
+      # step whether any tests failed.
       run: |
-        coverage run --source=dcoraid -m pytest tests
+        coverage run --source=dcoraid -m pytest tests || exit 0
     - name: Test whether test passed
-      if: ${{ failure() }}
         # check if pytest wrote failures to the "pytest-failures.txt" file
         # (exits 0 if the file does not exist)
       run: |
